### ISSUE TITLE
Not working in Chrome (ver 42)

### ISSUE THREAD

**Issue by eapyl** [asdf404/flummox-isomorphic-todo#1]
Looks like the problem in isomorphic-fetch plugin.

Picture with error: http://www.evernote.com/l/ACiufCVIcaREqJALRUg-77ioTUK6tD4IVkA/

Uncaught (in promise) TypeError: Illegal invocation {stack: (...), message: "Illegal invocation"}getTasks$ @ TodoActions.js:41tryCatch @ runtime.js:59invoke @ runtime.js:223Gp.(anonymous function) @ runtime.js:256tryCatch @ runtime.js:59step

**Comment by borodyadka** [comment]
@Udgin fixed. Tested in Chrome 42.

**Comment by vh** [comment]
This related to https://github.com/matthew-andrews/isomorphic-fetch/pull/20
