### ISSUE TITLE
Question about "app.use('/api', api);"

### ISSUE THREAD

**Issue by karantin2020** [asdf404/flummox-isomorphic-todo#3]
Цитата из статьи на хабре

> Теперь примонтируем роуты к основному приложению:
> 
> import api from './server/routes';
> // ...
> app.use('/api', api);

То же использование в /server/app.js:

> app.use('/api', api);

Не могу разобраться, что это за переменная api? В /server/routes.js этой переменной нет. В экспрессе тоже не смог найти ее.
По документации экспресса вместо api должен быть роутер

**Comment by vh** [comment]
Делается импорт модуля ./server/routes, в модуле routes в конце - export default router;
соответственно он и есть api, который добавляется в app.use

**Comment by karantin2020** [comment]
Спасибо за ответ. А нет ли ссылки на эти правила экспорта-импорта? Почему именно api? Или это имя отдается на усмотрение пользователя?

**Comment by borodyadka** [comment]
`export default router;` это тоже самое, что и `module.exports = router;` в старом синтаксисе. [Вот](http://www.2ality.com/2014/09/es6-modules-final.html) (en) хороший пост про модули.
